#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:include Layouts/helpScreen.kv
#:include Layouts/customs.kv
#:include Layouts/secondScreen.kv
#:include Layouts/myTabbedPanel.kv
#:include Layouts/homeScreen.kv
#:include Layouts/splashScreen.kv
#:include Layouts/closingHeader.kv

<RootScreen>:
    transition: FadeTransition()
    HomeScreen:
    SecondScreen:
    HelpScreen:
    SplashScreen:





